name: Build application

on:
  push:
    branches:
    - main
    

jobs:
  build-ubuntu:
    name: called workflow  
    uses: gtamang001/github-actions-test/.github/workflows/on-call-workflow.yml@main


