on: 
  push: 
jobs: 
  build-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: test condition fail
        if: $ {{startsWith(github.ref, cd)}}
        run: |
          echo " condition fail "
      - name: test condition pass 
        if: $ {{startsWith(github.ref, ci)}}
        run: |
          echo "condition pass .."
          ls -lah