name: Makes a cron commit 
on:
  push: 
    branches:
      - outputs
  # schedule:
  #   - cron: '0 8 * * *'
jobs: 
  cron-commit:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout 
        uses: actions/checkout@v2
        with: 
          fetch-depth: '0'
          ref: 'main'
      - name: commit it 
        run: |
          set -x
          git status
          git pull
          FILE=commit-file.txt
          if [ -f "$FILE" ]; then
              echo "$FILE exists."
              echo "making the commit"
              date > commit-file.txt
              echo "check if the changes are recorded"
              cat commit-file.txt
          else 
              echo "$FILE does not exist."
              touch commit-file.txt
              echo "making the commit now"
              date > commit-file.txt
              echo "Check if changes are recorded"
          fi
          git config --local user.email "ganga.bomzan@gmail.com"
          git config --local user.name "Ganga Tamang"
          git add -A
          git commit -m "added todays date"
          git push origin
