name: TEST MULTI MODULE TRIGGER ANOTHER WORKFLOW
on:
  push: 
    branches: 
      - feature-action-id
    paths:
      - 'dir/*'
jobs: 
  trigger-on-dir:
    runs-on: ubuntu-latest
    steps: 
      - name: Check if this runs 
        run: |
          echo "This trigger just happened from dir location"
          
