name: TEST OF PULL REQUEST FEATURES 
on: 
  push:
  # pull_request:
  #   types:
  #     - ready_for_review

jobs: 
  test-pull-request-major:
    runs-on: ubuntu-latest
    steps: 
      - name: Test of pull request 
        # if: ${{ github.event.label == 'major'}}
        run: |
          cat ${{github.github_event_path}}/workflow/event.json
          # echo '${{ toJSON(github.event) }}'
          # echo '${{ toJSON(github.event.pull_request.labels) }}' > labels.json
          # echo "cat labels .... json" 