name: TEST OF PULL REQUEST FEATURES 
on: 
  pull_request:
    types:
      - ready_for_review

jobs: 
  test-pull-request-major:
    runs-on: ubuntu-latest
    steps: 
      - name: Test of pull request 
        # if: ${{ github.event.label == 'major'}}
        run: |
          echo '${{ toJSON(github.event) }}'
          echo '${{ toJSON(github.event.pull_request.labels) }}'
          echo "Finally"
          echo "Test where you are  major ${{github.event.pull_request.labels.name}}"
  test-pull-request-minor: 
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps: 
      - name: Test of pull request 
        # if: ${{ github.event.label == 'minor'}}
        run: |
          echo "Test where you are  minor ${{github.event.pull_request.label}}"
  test-pull-request-patch: 
    if: ${{ github.event.pull_request.label == 'bug' }}
    runs-on: ubuntu-latest
    steps: 
      - name: Test of pull request
        # if: ${{ github.event.label == 'patch'}}
        run: |
          echo "Test where you are patch ${{github.ref}}"