name: CALLER WORKFLOW 

on:
  push:
    branches:
    - master

jobs:
  build-ubuntu:
    name: called workflow  
    uses: gtamang001/github-actions-test/.github/workflows/on-call-workflow.yml@main


