name: EXRACT VERSION FROM TAGS
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'ganga'

jobs: 
  deploy-job: 
    runs-on: ubuntu-latest
    environment: uat 
    steps: 
      - name: checkout code 
        uses: actions/checkout@v2
        with: 
          fetch-depth: '0'
      - name: Version setup 
        run: |
          echo "Setting version"
          version=$(git describe --tags --match "rel-[0-9]*-[0-9]*" | sed 's/-[^-]*//4g' | sed 's/rel-*//g' | sed 's/-/\./g')
          echo "version=$version"
          rm -f version.txt
          touch version.txt
          echo "${version}" > version.txt
          echo "Version set to $(cat version.txt)"
          echo "Version setup complete"
      - name: Version compare 
        run: |
          echo "The current version is $(cat version.txt) "